### ISSUE TITLE
Entries with (1)

### ISSUE THREAD

**Issue by badapplesdatabase** [opennorth/sfm-proxy#13]
We are using the (1) after names to indicate that this Person or Organization is the same - so in case of the 3 Armoured Division the (1) is used to capture the different AORs that the Division has.

Right now the (1) has been carried over in the import process -- eventually they need to be stripped out in some way

**Comment by jpmckinney** [comment]
Sites may still have "3 Armoured Division (1)'s base".

**Comment by badapplesdatabase** [comment]
OK --- how will we deal with that so there is no (1)'s in the final version?

**Comment by jpmckinney** [comment]
We can do a post-import clean.

**Comment by badapplesdatabase** [comment]
Sounds good!
