### ISSUE TITLE
Jurisdictions in Organization Dossiers

### ISSUE THREAD

**Issue by badapplesdatabase** [opennorth/sfm-proxy#17]
Example url: http://ffctn.com/clients/on/sfm/0.9.0/#country/ng/o/92bb9d0c-7c71-488d-9e71-80cf0069b635!date=2014-01-01&focus=map&overlay=organization-dossier

There are two different lists for the Jurisdictions in the right hand column --- this is confusing for users and not necessarily. One of the lists has dates, which is good, but those start and end dates don't have citations and the areas themselves have N/A-N/A after them - I'm not sure why that is.

**Comment by badapplesdatabase** [comment]
Sebestien noted that this was a backend issue, not a UI issue.

**Comment by jpmckinney** [comment]
@sebastien will have to be more specific. Looks like a presentation issue to me. If the `admin_level_1` and `admin_level_2` are unknown, it seems weird to display "N/A" instead of just displaying nothing. I think it's a _data_ issue - not a backend issue.

**Comment by jpmckinney** [comment]
Also, as far as I can tell, the UI is in fact displaying the same data twice. Both lists are using details from the organization's `areas`.

**Comment by sebastien** [comment]
I think we did not have a good understanding of how locations should be displayed. Right now the application is not working (backend connection seems down) so I cannot see exactly what the problem is. If you have a screenshot, that would be super helpful!

**Comment by badapplesdatabase** [comment]
![image](https://cloud.githubusercontent.com/assets/14323170/10168071/1c501326-6699-11e5-8a24-a80c65d24cbd.png)

Here is a screenshot from 81 Division

**Comment by sebastien** [comment]
Oh right, thanks. I think we had problems with understanding the location data structure and how the fields were used. In that case, I think we assumed the data was incomplete but would be completed later on. Could you describe the `location` object, and the role of each field, and wether they're optional or not? We can then work on having a clearer representation.

**Comment by badapplesdatabase** [comment]
There are two geographies attached to each Organization their *site*

**Comment by badapplesdatabase** [comment]
**site**

**Comment by badapplesdatabase** [comment]
Each Organization has two geographies related to it:
1. It's **Site**(s) - which includes the data fields: 
   - Headquarters (Barracks, Base, Physical Asset)
   - Source: Headquarters
   - Confidence: Headquarters
   - Headquarters GPS Latitude (if these exist this would inform the Site location on the Map)
   - Headquarters GPS Longitude (if these exist this would inform the Site location on the Map)
   - Source: Headquarters GPS
   - Confidence: Headquarters GPS
   - **and**
   - City or smallest administrative unit GeoName
   - City of smallest administrative unit GeonameID
   - Source: City of smallest administrative unit
   - Confidence: City of smallest administrative unit
   - ADMIN1 (state, province, governorate, or other largest administrative unit) Geoname
   - ADMIN1 (state, province, governorate, or other largest administrative unit) GeonameID
   - Source: ADMIN1
   - Confidence: ADMIN1
   - **and the dates for the Site are tied to:**
   - Date of first citation
   - Source: Date of first citation
   - Confidence: Date of first citation
   - Is this the founding date? (Y/N)
   - Date of last citation
   - Source: Date of last citation
   - Confidence: Date of last citation
   - Is this the dissolution date? (Y/N)
2. It's Area(s) of Operations (as noted in Google Docs - we should use this term in the UI in place of Jurisdictions or Areas of Responsibilities both of which convey a more legal/formal responsibility over an area that we can't always assume --- using the lowest common denominator of Area(s) of Operations avoids confusion and still gets the necessary information to the users) - which includes the data fields:
   - Area of Operations (Area of Responsibility Jurisdiction) Geoname (to be renamed in Google Sheets)
   - Area of Operations (Area of Responsibility, Jurisdiction) GeonameID (to be renamed in Google Sheets)
   - Source: Area of Operations (to be renamed in Google Sheets)
   - Confidence: Area of Operations (to be renamed in Google Sheets)
   - Date of first citation for area of operations (to be renamed in Google Sheets)
   - Source: Date of first citation for area of operations (to be renamed in Google Sheets)
   - Confidence: Date of first citation for area of operations (to be renamed in Google Sheets)
   - Date of last citation for area of operations (to be renamed in Google Sheets)
   - Source: Date of last citation for area of operations (to be renamed in Google Sheets)
   - Confidence: Date of last citation for area of operations (to be renamed in Google Sheets)
   - Area of Operations assumed to current date? Y/N (addition as discussed in separate thread with James) https://github.com/opennorth/sfm-proxy/issues/11

**Comment by badapplesdatabase** [comment]
**Site**(s) are currently displayed in the dossier like this:

![image](https://cloud.githubusercontent.com/assets/14323170/10172235/533232a8-66ac-11e5-9b43-c6ebc2767663.png)

url : http://ffctn.com/clients/on/sfm/0.9.0/#country/ng/o/92bb9d0c-7c71-488d-9e71-80cf0069b635!date=2014-01-01&focus=map&overlay=organization-dossier

Or when there is a _Headquarters (Barracks, Base, Physical Asset)_ field like this:

![image](https://cloud.githubusercontent.com/assets/14323170/10172277/871f3e08-66ac-11e5-9221-07f8eaf75025.png)

url: http://ffctn.com/clients/on/sfm/0.9.0/#country/ng/o/278c27c9-b3e4-4800-93e2-855324e0b423!date=2014-01-01&focus=map&overlay=organization-dossier

**Comment by badapplesdatabase** [comment]
And the _Date of first citation_ and _Date of last citation_ are displayed in a separate location here: 

![image](https://cloud.githubusercontent.com/assets/14323170/10172387/0354b5ca-66ad-11e5-91aa-7686cffed91a.png)

url : http://ffctn.com/clients/on/sfm/0.9.0/#country/ng/o/92bb9d0c-7c71-488d-9e71-80cf0069b635!date=2014-01-01&focus=map&overlay=organization-dossier   (same url as first example above)

**Comment by sebastien** [comment]
I think it would be _much_ easier if there was a field `location` with a human-readable value for the location, as the root of the problem (on the UI) is complicated logic (to me) of creating a presentable location from the city/admin_area_1/admin_area_2 fields.

And yes, we should make it clear (in the interface) the distinction between sites and jurisdictions/areas of operations. The presentation will be clearer if be have the human-readable `location` field for both.

**Comment by badapplesdatabase** [comment]
Hi Sebastien --- I think we can do both while keeping the current data model. We are pretty close already.

For the section **Headquarters** (which we should rename to **Bases** since some Organizations have multiple bases and determining which one is truly the "headquarters" would complicate things unnecessarily, and not be that helpful to users) the logic for the UI should be:

**Headquarters (Barracks, Base, Physical Asset)** - **City or smallest administrative unit GeoName** - **ADMIN1 (state, province, governorate, or other largest administrative unit) Geoname** 

It seems like the UI is already doing that as shown here:

![image](https://cloud.githubusercontent.com/assets/14323170/10195996/8a5619ae-675e-11e5-9981-a88037a0b112.png)

When Headquarters is blank we'd just use "**Name**'s base in" so it would be something like this:

![image](https://cloud.githubusercontent.com/assets/14323170/10196065/e8a9c582-675e-11e5-9062-bfb27cdf2444.png)

**Comment by badapplesdatabase** [comment]
For Area(s) of Operations we'd just use **Area of Operations (Area of Responsibility Jurisdiction) Geoname**

Geonames are always human readable so it should be easy to have them display in the UI

**Comment by badapplesdatabase** [comment]
The reason I want to keep the current data model is it relies on Geonames which forces standardization for data entry AND has external data model that other projects can use to quickly plug the Monitor's data into their work.

Also - in terms of UI if we just used **location** (which I'm assuming would be the smallest Geoname possible) we'd lose the valuable nuance of: we have High Confidence this Organization is based in Lagos State, but Low Confidence that its based in the city of Lagos.  Additionally - many countries have  states/provinces and cities with the same name so for instance if we just had a **location** of Lagos it wouldn't be clear if that meant the city of Lagos or the state of Lagos. A user would have to consult the Map or otherwise complicate their workflow.

**Comment by sebastien** [comment]
Thanks for the clarification, I think I meant `location` _in addition_ to the other fields. The logic you described is still quite complex for formatting, and it's common practice for object to have machine-processable fields (`lat`/`lng`, `admin1`, `admin2`, etc) in addition to human-readable fields (`location`).

It's technically possible to implement it on the front-end, but anyone using the SFM API will have the same trouble of finding how to present the location in human-readable form, which is why I think it's better to do that on the back-end and let the front-end display `location` verbatim.

**Comment by badapplesdatabase** [comment]
Ok so you're proposing that the `location` for

![image](https://cloud.githubusercontent.com/assets/14323170/10202539/5bfd1a96-677f-11e5-8d4b-5776540951f0.png)

would be Dalet Barracks - Kaduna - Kaduna State, right?  That's what would be in that field on the backend. Or basically whatever we decide to put would be what is displayed in the UI text.

**Comment by badapplesdatabase** [comment]
@jpmckinney does this defeat the purpose of using Geonames as the gazetter?

**Comment by jpmckinney** [comment]
I think we can just have the API calculate what the location text should be based on the other fields, if it’s too much trouble for the UI to do it.

**Comment by badapplesdatabase** [comment]
@jpmckinney does it complicate the API to have to do this?  If adding `location` would simplify things for everyone AND still make the geocoding through Geonames work for other projects wanting to use SFM data that could work.  We'd need several `location` columns for different languages, but that could work....

**Comment by jpmckinney** [comment]
It won't be too complicated.

**Comment by badapplesdatabase** [comment]
Ok great!

**Comment by sebastien** [comment]
What we do in that case (i18n) is to do the following: `location:{en:"English location...", fr:"French location", ...}`

**Comment by badapplesdatabase** [comment]
At this point I'm planning for the Monitor to have/expand to the following languages:

English, Spanish, Arabic, French, Portuguese, Russian, Indonesian

It could expand outside of that, but I think that's already plenty ambitious/realistic given target user base.

**Comment by jpmckinney** [comment]
The `location` field is specified in this issue as a concatenation of other fields. Those fields are (to date) not translated. So, for the time being, let's leave `location` as one simple field.

**Comment by jpmckinney** [comment]
UI can be updated to use the new `location` field. See #23 for new issue.
