### ISSUE TITLE
Names for Organizations in multiple languages

### ISSUE THREAD

**Issue by badapplesdatabase** [opennorth/sfm-proxy#18]
Should we update the data template to have names for Organizations in multiple languages? As of right now there is no clear way for the API and thus the UI to display the name in different languages.

I could add columns for each of the target languages that the Monitor could realistically expand to: English, Spanish, Arabic, French, Portuguese, Russian, Indonesian

The Source: Name column and Confidence: Name columns would apply to all the different Names in different languages.

I'm fine with keeping all the Aliases together in one column even if that means mixing languages.

**Comment by jpmckinney** [comment]
I think we should stick with the past solution of mixing languages, as otherwise we're changing the scope.
