### ISSUE TITLE
Map "base"

### ISSUE THREAD

**Issue by badapplesdatabase** [opennorth/sfm-proxy#25]
While the current map is a stylized representation of Nigeria - I've been assuming that the base map will be a Google Map or Open Street Map or some other base that will give users context in navigating the map.

**Comment by jpmckinney** [comment]
/cc @sebastien

I assume this needed to have been brought up during the design process.

**Comment by sebastien** [comment]
The design featured a simplified world map, so that's what we used. We wanted to have a schematic map as the UI is already very information-rich, and the initial map is used to select the countries with data (Google maps does not allow to select a specific country).

**Comment by badapplesdatabase** [comment]
Ok let's drop/close this.

**Comment by badapplesdatabase** [comment]
Ok -- let's drop/close this.
