### ISSUE TITLE
Re-run import

### ISSUE THREAD

**Issue by jpmckinney** [opennorth/sfm-proxy#7]
- See what data is missing
- Check that Police is added

**Comment by badapplesdatabase** [comment]
Hi James ---I've been doing by best to clean up the Nigeria dataset --- and update the Mexico dataset as well.  I think it might make your life easier if I share "clean" sets for the next import. Can you give me an ETA for when you would need that and I'll work to get you as much as possible by that date.

**Comment by jpmckinney** [comment]
The latest Nigeria import seems to be pretty clean, except there's still issue #21 to resolve.

For other countries, I think I should import them into Caravan's system instead of importing them into the the stop-gap database I have now.

**Comment by badapplesdatabase** [comment]
Good to hear about the data - still in process of cleaning it up - let me know if my continuing editing/adding is making anything difficult for you. 

Makes sense using Caravan's system for importing other countries.
